# Generated by Django 4.0.3 on 2022-04-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_Id', models.AutoField(primary_key=True, serialize=False)),
                ('installedDate', models.DateTimeField(default=None)),
                ('isMQ135', models.BooleanField(default=False)),
                ('isMQ5', models.BooleanField(default=False)),
                ('isMQ7', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, default=0)),
                ('longitude', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pollution_Data',
            fields=[
                ('data_Id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=None)),
                ('mq135', models.FloatField(blank=True, default=0)),
                ('mq5', models.FloatField(blank=True, default=0)),
                ('mq7', models.FloatField(blank=True, default=0)),
                ('alert', models.BooleanField(default=False)),
                ('node_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.node')),
            ],
        ),
    ]
