# Generated by Django 4.0.3 on 2022-05-06 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_Id', models.AutoField(primary_key=True, serialize=False)),
                ('installedDate', models.DateField(default=datetime.date(2022, 5, 6))),
                ('mq135', models.FloatField(blank=True, default=0)),
                ('location', models.CharField(blank=True, default='None', help_text='Enter location of the node', max_length=128)),
                ('alert', models.BooleanField(default=False)),
                ('macAddress', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pollution_Data',
            fields=[
                ('data_Id', models.AutoField(primary_key=True, serialize=False)),
                ('datetimestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('mq135', models.FloatField(blank=True, default=0)),
                ('macAddress', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='myapp.node', to_field='macAddress')),
            ],
        ),
    ]
