# Generated by Django 4.0.3 on 2022-03-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pollution_Data',
            fields=[
                ('data_Id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=None)),
                ('mq135', models.FloatField(blank=True, default=0)),
                ('mq5', models.FloatField(blank=True, default=0)),
                ('mq7', models.FloatField(blank=True, default=0)),
                ('temp', models.FloatField(blank=True, default=0)),
                ('humidity', models.FloatField(blank=True, default=0)),
                ('alert', models.BooleanField(default=False)),
            ],
        ),
    ]
