# Generated by Django 4.0.3 on 2022-04-30 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='installedDate',
            field=models.DateField(default=datetime.date(2022, 4, 30)),
        ),
        migrations.AlterField(
            model_name='pollution_data',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
