# Generated by Django 4.0.3 on 2022-04-15 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollution_data',
            name='alert',
        ),
        migrations.AddField(
            model_name='node',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='installedDate',
            field=models.DateField(default=datetime.date(2022, 4, 15)),
        ),
        migrations.AlterField(
            model_name='pollution_data',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 13, 46, 23, 519785)),
        ),
    ]
