# Generated by Django 4.0.3 on 2022-05-01 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_node_installeddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollution_data',
            old_name='datetime',
            new_name='datetimestamp',
        ),
        migrations.AlterField(
            model_name='node',
            name='installedDate',
            field=models.DateField(default=datetime.date(2022, 5, 1)),
        ),
    ]
