# Generated by Django 4.0.3 on 2022-04-15 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_pollution_data_alert_node_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollution_data',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 13, 46, 40, 676347)),
        ),
    ]
