# Generated by Django 4.0.3 on 2022-04-15 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pollution_data_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollution_data',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
