# Generated by Django 4.0.3 on 2022-05-01 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_node_installeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='installedDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 1, 14, 25, 58, 657195, tzinfo=utc)),
        ),
    ]
