# Generated by Django 4.0.3 on 2022-05-01 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_node_installeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='installedDate',
            field=models.DateField(default=datetime.date(2022, 5, 1)),
        ),
    ]
