# Generated by Django 4.0.3 on 2022-05-03 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_node_installeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='isMQ135',
        ),
        migrations.RemoveField(
            model_name='node',
            name='isMQ5',
        ),
        migrations.RemoveField(
            model_name='node',
            name='isMQ7',
        ),
        migrations.RemoveField(
            model_name='node',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='node',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='node',
            name='mq5',
        ),
        migrations.RemoveField(
            model_name='node',
            name='mq7',
        ),
        migrations.RemoveField(
            model_name='pollution_data',
            name='mq5',
        ),
        migrations.RemoveField(
            model_name='pollution_data',
            name='mq7',
        ),
        migrations.AddField(
            model_name='node',
            name='location',
            field=models.CharField(default='None', help_text='Enter location of the node', max_length=128),
        ),
        migrations.AlterField(
            model_name='node',
            name='installedDate',
            field=models.DateField(default=datetime.date(2022, 5, 3)),
        ),
    ]
