# Generated by Django 4.0.3 on 2022-05-06 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_node_ismq135_remove_node_ismq5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='macAddress',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='node',
            name='installedDate',
            field=models.DateField(default=datetime.date(2022, 5, 6)),
        ),
    ]
