# Generated by Django 4.0.3 on 2022-05-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pollution_data_macaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='location',
            field=models.CharField(blank=True, default='None', help_text='Enter location of the node', max_length=128),
        ),
    ]
